export default {
  CHANGE_USER: 'CHANGE_USER',
  CHANGE_USERID: 'CHANGE_USERID',
  CHANGE_ALG: 'CHANGE_ALG',
  GET_COMMON_HISTORY_LIST: 'GET_COMMON_HISTORY_LIST',
  GET_RECOMMEND_LIST_1: 'GET_RECOMMEND_LIST_1',
  GET_RECOMMEND_LIST_2: 'GET_RECOMMEND_LIST_2',
  GET_RECOMMEND_LIST_3: 'GET_RECOMMEND_LIST_3',
  GET_RECOMMEND_LIST_4: 'GET_RECOMMEND_LIST_4',
  GET_LIKE_LIST: 'GET_LIKE_LIST',
  GET_HISTORY_LIST: 'GET_HISTORY_LIST',
}
